<?php

return [
    "invoice_title" => "Invoice #:invoice_number",
    "invoice_date" => "Invoice date: :date",
    "invoice_customer" => "Customer:",
    "invoice_email" => "Email:",
    "invoice_content" => "Cart content:",
    "invoice_product" => "Product",
    "invoice_quantity" => "Qty",
    "invoice_unit_price" => "Unit price",
    "invoice_total_price" => "Total price",
    "invoice_subtotal" => "Subtotal",
    "invoice_refunded" => "Refunded:",
    "invoice_balance_due" => "Balance due:",
    "invoice_total_paid" => "Total paid:",
    "invoice_thank_you" => "Thank you for your purchase on :app_name !",
    "invoice_generated" => "This invoice was automatically generated by :app_name and is valid without signature.",
];
